Repository Side-Project-Planting/Backend, pull requests merged in 2023-11, with the labels that each got.

#65 [#62, #63] 라벨 생성, 삭제 기능 구현
  plan-service/src/main/java/com/example/planservice/application/LabelService.java
  plan-service/src/main/java/com/example/planservice/application/dto/LabelDeleteServiceRequest.java
  plan-service/src/main/java/com/example/planservice/domain/label/Label.java
  plan-service/src/main/java/com/example/planservice/domain/label/repository/LabelRepository.java
  plan-service/src/main/java/com/example/planservice/domain/plan/Plan.java
  plan-service/src/main/java/com/example/planservice/exception/ErrorCode.java
  plan-service/src/main/java/com/example/planservice/presentation/LabelController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/LabelCreateRequest.java
  plan-service/src/test/java/com/example/planservice/application/LabelServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/PlanMembershipVerificationServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/TabServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/TaskServiceTest.java
  plan-service/src/test/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/domain/tab/TabGroupTest.java
  plan-service/src/test/java/com/example/planservice/domain/task/repository/TaskRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/interceptor/AuthenticationInterceptorTest.java
  plan-service/src/test/java/com/example/planservice/presentation/LabelControllerTest.java
Labels: feature

#68 [#67] Plan Service 리팩토링
  plan-service/src/main/java/com/example/planservice/application/LabelService.java
  plan-service/src/main/java/com/example/planservice/application/PlanMembershipService.java
  plan-service/src/main/java/com/example/planservice/application/TabService.java
  plan-service/src/main/java/com/example/planservice/application/TaskService.java
  plan-service/src/main/java/com/example/planservice/domain/label/Label.java
  plan-service/src/main/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepository.java
  plan-service/src/main/java/com/example/planservice/domain/plan/Plan.java
  plan-service/src/main/java/com/example/planservice/domain/tab/Tab.java
  plan-service/src/main/java/com/example/planservice/domain/tab/TabGroup.java
  plan-service/src/main/java/com/example/planservice/domain/task/Task.java
  plan-service/src/main/java/com/example/planservice/exception/GlobalExceptionHandler.java
  plan-service/src/main/java/com/example/planservice/presentation/TaskController.java
  plan-service/src/main/resources/application-test.yml
  plan-service/src/main/resources/data.sql
  plan-service/src/test/java/com/example/planservice/application/LabelServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/PlanMembershipServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/PlanMembershipVerificationServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/TabServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/TaskServiceTest.java
  plan-service/src/test/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/domain/tab/TabGroupTest.java
  plan-service/src/test/java/com/example/planservice/domain/tab/TabTest.java
  plan-service/src/test/java/com/example/planservice/presentation/LabelControllerTest.java
  plan-service/src/test/java/com/example/planservice/presentation/TaskControllerTest.java
Labels: refactoring

#71 [#69,#70] 회원가입 로직 구현
  auth-service/src/main/java/com/example/auth/application/AuthService.java
  auth-service/src/main/java/com/example/auth/application/dto/response/OAuthLoginResponse.java
  auth-service/src/main/java/com/example/auth/application/dto/response/OAuthUserResponse.java
  auth-service/src/main/java/com/example/auth/application/dto/response/RegisterResponse.java
  auth-service/src/main/java/com/example/auth/client/MemberServiceClient.java
  auth-service/src/main/java/com/example/auth/client/MemberServiceClientImpl.java
  auth-service/src/main/java/com/example/auth/client/MemberServiceProperties.java
  auth-service/src/main/java/com/example/auth/client/dto/MemberRegisterRequest.java
  auth-service/src/main/java/com/example/auth/client/dto/MemberRegisterResponse.java
  auth-service/src/main/java/com/example/auth/domain/AuthInfoRepository.java
  auth-service/src/main/java/com/example/auth/domain/OAuthInfo.java
  auth-service/src/main/java/com/example/auth/exception/ErrorCode.java
  auth-service/src/main/java/com/example/auth/exception/ErrorResponse.java
  auth-service/src/main/java/com/example/auth/exception/GlobalExceptionHandler.java
  auth-service/src/main/java/com/example/auth/exception/MicroserviceException.java
  auth-service/src/main/java/com/example/auth/oauth/google/GoogleOAuthClient.java
  auth-service/src/main/java/com/example/auth/presentation/AuthController.java
  auth-service/src/main/java/com/example/auth/presentation/dto/request/RegisterRequest.java
  auth-service/src/main/resources/application-test.yml
  auth-service/src/main/resources/data.sql
  auth-service/src/test/java/com/example/auth/application/AuthServiceTest.java
  auth-service/src/test/java/com/example/auth/domain/AuthInfoRepositoryTest.java
  auth-service/src/test/java/com/example/auth/domain/OAuthInfoTest.java
  auth-service/src/test/java/com/example/auth/presentation/AuthControllerTest.java
  auth-service/src/test/resources/application.yml
  plan-service/src/main/java/com/example/planservice/application/MemberService.java
  plan-service/src/main/java/com/example/planservice/application/dto/MemberRegisterResponse.java
  plan-service/src/main/java/com/example/planservice/config/WebConfig.java
  plan-service/src/main/java/com/example/planservice/domain/member/Member.java
  plan-service/src/main/java/com/example/planservice/domain/member/repository/MemberRepository.java
  plan-service/src/main/java/com/example/planservice/exception/ErrorCode.java
  plan-service/src/main/java/com/example/planservice/interceptor/AuthenticationInterceptor.java
  plan-service/src/main/java/com/example/planservice/presentation/MemberController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/MemberRegisterRequest.java
  plan-service/src/test/java/com/example/planservice/application/MemberServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/PlanMembershipServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/dto/MemberRegisterResponseTest.java
  plan-service/src/test/java/com/example/planservice/domain/member/MemberTest.java
  plan-service/src/test/java/com/example/planservice/domain/member/repository/MemberRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/interceptor/AuthenticationInterceptorTest.java
  plan-service/src/test/java/com/example/planservice/presentation/MemberControllerTest.java
  plan-service/src/test/java/com/example/planservice/presentation/TabControllerTest.java
Labels: feature

#74 hotfix: id_ed25519.txt, known_hosts.txt gitignore 처리
  .gitignore
Labels: deploy

#73 [#34, #72] 플랜 조회, 초대 API 구현
  .gitignore
  plan-service/src/main/java/com/example/planservice/application/LabelService.java
  plan-service/src/main/java/com/example/planservice/application/PlanService.java
  plan-service/src/main/java/com/example/planservice/application/TabService.java
  plan-service/src/main/java/com/example/planservice/domain/Linkable.java
  plan-service/src/main/java/com/example/planservice/domain/plan/Plan.java
  plan-service/src/main/java/com/example/planservice/domain/tab/Tab.java
  plan-service/src/main/java/com/example/planservice/domain/task/Task.java
  plan-service/src/main/java/com/example/planservice/presentation/PlanController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/LabelOfPlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/MemberOfPlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/PlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TabOfPlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TaskOfPlanResponse.java
  plan-service/src/test/java/com/example/planservice/application/PlanServiceTest.java
  plan-service/src/test/java/com/example/planservice/presentation/PlanControllerTest.java
Labels: feature

#81 [#80] 멤버 단건 조회 기능 구현
  plan-service/src/main/java/com/example/planservice/application/MemberService.java
  plan-service/src/main/java/com/example/planservice/config/WebConfig.java
  plan-service/src/main/java/com/example/planservice/domain/member/Member.java
  plan-service/src/main/java/com/example/planservice/interceptor/AuthenticationInterceptor.java
  plan-service/src/main/java/com/example/planservice/presentation/MemberController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/MemberFindResponse.java
  plan-service/src/test/java/com/example/planservice/application/MemberServiceTest.java
  plan-service/src/test/java/com/example/planservice/interceptor/AuthenticationInterceptorTest.java
  plan-service/src/test/java/com/example/planservice/presentation/MemberControllerTest.java
Labels: feature

#83 [#82] docker-compose 오류해결
  docker-compose.yml
  init.sql
Labels: bugfix

#84 [#79] 탭 단건 조회 기능 구현
  .gitignore
  plan-service/src/main/java/com/example/planservice/application/TabService.java
  plan-service/src/main/java/com/example/planservice/presentation/TabController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TabFindResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TabRetrieveResponse.java
  plan-service/src/test/java/com/example/planservice/application/TabServiceTest.java
  plan-service/src/test/java/com/example/planservice/presentation/TabControllerTest.java
Labels: feature

#85 [#78] 라벨 단건 조회 기능 구현
  plan-service/src/main/java/com/example/planservice/application/LabelService.java
  plan-service/src/main/java/com/example/planservice/presentation/LabelController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/LabelFindResponse.java
  plan-service/src/test/java/com/example/planservice/application/LabelServiceTest.java
  plan-service/src/test/java/com/example/planservice/presentation/LabelControllerTest.java
Labels: feature

#89 [#29, #30, #33, #86, #87, #88] 플랜 설정, 나가기, 추방, 멤버id 조회 구현 및 리팩토링
  plan-service/src/main/java/com/example/planservice/application/EmailService.java
  plan-service/src/main/java/com/example/planservice/application/PlanService.java
  plan-service/src/main/java/com/example/planservice/application/TabService.java
  plan-service/src/main/java/com/example/planservice/domain/Linkable.java
  plan-service/src/main/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepository.java
  plan-service/src/main/java/com/example/planservice/domain/plan/Plan.java
  plan-service/src/main/java/com/example/planservice/domain/tab/Tab.java
  plan-service/src/main/java/com/example/planservice/domain/task/Task.java
  plan-service/src/main/java/com/example/planservice/presentation/PlanController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/PlanKickRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/PlanUpdateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/CreateResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/LabelOfPlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/MemberOfPlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/PlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/PlanTitleIdResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TabOfPlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TaskOfPlanResponse.java
  plan-service/src/test/java/com/example/planservice/application/EmailServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/PlanServiceTest.java
  plan-service/src/test/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/domain/plan/PlanTest.java
  plan-service/src/test/java/com/example/planservice/presentation/PlanControllerTest.java
Labels: feature, refactoring

#90 [#77] 태스크 단건 조회 기능 구현
  plan-service/src/main/java/com/example/planservice/application/TaskService.java
  plan-service/src/main/java/com/example/planservice/domain/task/Task.java
  plan-service/src/main/java/com/example/planservice/presentation/TaskController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TaskFindResponse.java
  plan-service/src/test/java/com/example/planservice/application/TaskServiceTest.java
  plan-service/src/test/java/com/example/planservice/presentation/TaskControllerTest.java
Labels: feature

#93 [#92, #91] API 연동시 발생한 버그 수정
  auth-service/src/main/java/com/example/auth/AuthServiceApplication.java
  gateway-service/src/main/java/com/example/gatewayservice/GatewayServiceApplication.java
  plan-service/src/main/java/com/example/planservice/PlanServiceApplication.java
  plan-service/src/main/java/com/example/planservice/application/PlanService.java
  plan-service/src/main/java/com/example/planservice/application/TaskService.java
  plan-service/src/main/java/com/example/planservice/domain/task/Task.java
  plan-service/src/main/java/com/example/planservice/presentation/PlanController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/TaskCreateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TaskFindResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TaskOfPlanResponse.java
  plan-service/src/test/java/com/example/planservice/application/PlanServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/TaskServiceTest.java
  plan-service/src/test/java/com/example/planservice/presentation/PlanControllerTest.java
Labels: bugfix

#95 [#94] 리프레쉬 토큰을 쿠키 방식으로 발급하도록 변경
  .gitignore
  auth-service/src/main/java/com/example/auth/application/AuthService.java
  auth-service/src/main/java/com/example/auth/application/dto/response/OAuthLoginResponse.java
  auth-service/src/main/java/com/example/auth/application/dto/response/OAuthUserResponse.java
  auth-service/src/main/java/com/example/auth/application/dto/response/RegisterResponse.java
  auth-service/src/main/java/com/example/auth/client/MemberServiceClientImpl.java
  auth-service/src/main/java/com/example/auth/domain/OAuthInfo.java
  auth-service/src/main/java/com/example/auth/domain/member/Member.java
  auth-service/src/main/java/com/example/auth/domain/member/MemberRepository.java
  auth-service/src/main/java/com/example/auth/exception/ErrorCode.java
  auth-service/src/main/java/com/example/auth/jwt/TokenInfo.java
  auth-service/src/main/java/com/example/auth/presentation/AuthController.java
  auth-service/src/main/java/com/example/auth/presentation/dto/request/TokenRefreshRequest.java
  auth-service/src/main/resources/data.sql
  auth-service/src/test/java/com/example/auth/application/AuthServiceTest.java
  auth-service/src/test/java/com/example/auth/domain/AuthInfoRepositoryTest.java
  auth-service/src/test/java/com/example/auth/domain/OAuthInfoTest.java
  auth-service/src/test/java/com/example/auth/domain/member/MemberTest.java
  auth-service/src/test/java/com/example/auth/presentation/AuthControllerTest.java
  auth-service/src/test/resources/application.yml
Labels: refactoring

#108 fix: 플랜 조회 시 500번 에러가 발생하는 이슈 해결
  plan-service/src/main/java/com/example/planservice/domain/tab/Tab.java
Labels: bug

#110 [#109] CORS 검사하는 로직을 Gateway에게 위임
  auth-service/src/main/java/com/example/auth/config/WebConfig.java
  gateway-service/src/main/java/com/example/gatewayservice/config/SecurityConfig.java
Labels: enhancement

#115 [#113, #114] Access-Control-Allow-Origin 헤더가 2개 생기는 오류를 해결했습니다.
  auth-service/src/main/java/com/example/auth/config/WebConfig.java
  gateway-service/src/main/java/com/example/gatewayservice/config/SecurityConfig.java
  plan-service/src/main/java/com/example/planservice/config/WebConfig.java
Labels: bug

#116 [#114] Access-Control-Allow-Origin 헤더가 2개 생기는 오류를 해결했습니다. -2차
  auth-service/src/main/java/com/example/auth/config/WebConfig.java
  auth-service/src/main/java/com/example/auth/interceptor/CorsInvalidateInterceptor.java
  config-service/src/test/java/com/example/configservice/ConfigServiceApplicationTests.java
  plan-service/src/main/java/com/example/planservice/config/WebConfig.java
  plan-service/src/main/java/com/example/planservice/interceptor/CorsInvalidateInterceptor.java
Labels: bug

#106 [#104, #105] 플랜 초대 로직 및 플랜 수정 로직 변경
  build.gradle
  docker-compose.yml
  plan-service/build.gradle
  plan-service/src/main/java/com/example/planservice/application/EmailService.java
  plan-service/src/main/java/com/example/planservice/application/PlanService.java
  plan-service/src/main/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepository.java
  plan-service/src/main/java/com/example/planservice/exception/ErrorCode.java
  plan-service/src/main/java/com/example/planservice/presentation/PlanController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/PlanUpdateRequest.java
  plan-service/src/main/java/com/example/planservice/util/RedisUtils.java
  plan-service/src/test/java/com/example/planservice/application/EmailServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/LabelServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/MemberServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/PlanMembershipServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/PlanServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/TabServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/TaskServiceTest.java
  plan-service/src/test/java/com/example/planservice/application/dto/MemberRegisterResponseTest.java
  plan-service/src/test/java/com/example/planservice/config/TestConfig.java
  plan-service/src/test/java/com/example/planservice/domain/member/repository/MemberRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/domain/tab/TabGroupTest.java
  plan-service/src/test/java/com/example/planservice/domain/tab/repository/TabRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/domain/task/repository/TaskRepositoryTest.java
  plan-service/src/test/java/com/example/planservice/interceptor/AuthenticationInterceptorTest.java
  plan-service/src/test/java/com/example/planservice/presentation/PlanControllerTest.java
  plan-service/src/test/resources/application.yml
Labels: enhancement

#112 [#103] Gateway에 스웨거 연동
  .gitignore
  auth-service/build.gradle
  auth-service/src/main/java/com/example/auth/config/SwaggerConfig.java
  auth-service/src/main/java/com/example/auth/presentation/AuthController.java
  auth-service/src/test/resources/application.yml
  gateway-service/build.gradle
  gateway-service/src/main/java/com/example/gatewayservice/config/SwaggerConfig.java
  gateway-service/src/main/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  plan-service/build.gradle
  plan-service/src/main/java/com/example/planservice/config/SwaggerConfig.java
  plan-service/src/main/java/com/example/planservice/interceptor/AuthenticationInterceptor.java
  plan-service/src/test/resources/application.yml
Labels: feature
