Repository Side-Project-Planting/Backend, pull requests merged in 2023-12, with the labels that each got.

#117 [#20] 메인페이지 API 추가 및 플랜 조회 테스트 리팩토링
  plan-service/src/main/java/com/example/planservice/application/PlanService.java
  plan-service/src/main/java/com/example/planservice/domain/memberofplan/repository/MemberOfPlanRepository.java
  plan-service/src/main/java/com/example/planservice/domain/plan/Plan.java
  plan-service/src/main/java/com/example/planservice/domain/tab/TabGroup.java
  plan-service/src/main/java/com/example/planservice/domain/task/Task.java
  plan-service/src/main/java/com/example/planservice/presentation/PlanController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/PlanMainResponse.java
  plan-service/src/test/java/com/example/planservice/application/PlanServiceTest.java
Labels: feature

#118 [#111] Swagger를 사용한 문서작업
  auth-service/src/main/java/com/example/auth/application/dto/response/GetAuthorizedUriResponse.java
  auth-service/src/main/java/com/example/auth/application/dto/response/OAuthLoginResponse.java
  auth-service/src/main/java/com/example/auth/application/dto/response/RegisterResponse.java
  auth-service/src/main/java/com/example/auth/jwt/TokenInfo.java
  auth-service/src/main/java/com/example/auth/presentation/AuthController.java
  auth-service/src/main/java/com/example/auth/presentation/dto/request/OAuthLoginRequest.java
  auth-service/src/main/java/com/example/auth/presentation/dto/request/RegisterRequest.java
  plan-service/src/main/java/com/example/planservice/application/dto/TabChangeTitleResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/LabelController.java
  plan-service/src/main/java/com/example/planservice/presentation/MemberController.java
  plan-service/src/main/java/com/example/planservice/presentation/PlanController.java
  plan-service/src/main/java/com/example/planservice/presentation/TabController.java
  plan-service/src/main/java/com/example/planservice/presentation/TaskController.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/LabelCreateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/MemberRegisterRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/PlanCreateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/PlanKickRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/PlanUpdateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/TabChangeOrderRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/TabChangeTitleRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/TabCreateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/TaskCreateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/request/TaskUpdateRequest.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/LabelFindResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/MemberFindResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/PlanResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/PlanTitleIdResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TabChangeOrderResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TabFindResponse.java
  plan-service/src/main/java/com/example/planservice/presentation/dto/response/TaskFindResponse.java
Labels: documentation, feature

#120 [#119]YML 파일을 사용해 쿠키를 관리하도록 변경
  auth-service/src/main/java/com/example/auth/config/ConfigurationPropertiesConfig.java
  auth-service/src/main/java/com/example/auth/presentation/AuthController.java
  auth-service/src/main/java/com/example/auth/presentation/CustomCookieManager.java
  auth-service/src/main/java/com/example/auth/presentation/CustomCookiesProperties.java
  auth-service/src/test/java/com/example/auth/presentation/AuthControllerTest.java
  auth-service/src/test/java/com/example/auth/presentation/CustomCookieManagerTest.java
Labels: refactoring

#124 [#123] Authorized Uri 요청을 localhost:3000에서 보낸 경우 redirect url에 localhost:3000을 넣어서 보내준다.
  auth-service/src/main/java/com/example/auth/application/AuthService.java
  auth-service/src/main/java/com/example/auth/presentation/AuthController.java
  auth-service/src/test/java/com/example/auth/application/AuthServiceTest.java
  auth-service/src/test/java/com/example/auth/presentation/AuthControllerTest.java
Labels: feature

#125 [#123] Authorized Uri 요청을 localhost:3000에서 보낸 경우 redirect url에 localhost:3000을 넣어서 보내준다. (로직 추가)
  auth-service/src/main/java/com/example/auth/application/AuthService.java
  auth-service/src/main/java/com/example/auth/oauth/OAuthClient.java
  auth-service/src/main/java/com/example/auth/oauth/OAuthProvider.java
  auth-service/src/main/java/com/example/auth/oauth/google/GoogleOAuthClient.java
  auth-service/src/main/java/com/example/auth/presentation/AuthController.java
Labels: feature

#126 [#114]Access-Control-Allow-Origin 헤더가 2개 생기는 오류를 해결했습니다. -3차
  auth-service/src/main/java/com/example/auth/interceptor/CorsInvalidateInterceptor.java
  auth-service/src/main/java/com/example/auth/oauth/google/GoogleOAuthClient.java
  plan-service/src/main/java/com/example/planservice/interceptor/CorsInvalidateInterceptor.java
Labels: bugfix

#128 [#127] 탭 삭제 시 발생하는 "태스크가 존재하지 않는다" 오류 해결
  plan-service/src/main/java/com/example/planservice/application/TabService.java
  plan-service/src/main/java/com/example/planservice/domain/tab/Tab.java
  plan-service/src/main/java/com/example/planservice/domain/task/repository/TaskRepository.java
Labels: bugfix
